# Configuração do Wrangler para Cloudflare Pages
name = "neorastro"
compatibility_date = "2024-01-01"

# Configuração para Pages
[env.production]
compatibility_flags = ["nodejs_compat"]

# Banco de dados D1
[[env.production.d1_databases]]
binding = "DB"
database_name = "neorastro-db"
database_id = "seu-database-id-aqui"

# Variáveis de ambiente
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "v1"

# Configuração para desenvolvimento local
[env.preview]
compatibility_flags = ["nodejs_compat"]

[[env.preview.d1_databases]]
binding = "DB"
database_name = "neorastro-db-preview"
database_id = "seu-preview-database-id-aqui"